import 'bootstrap/dist/css/bootstrap.min.css';
import 'font-awesome/css/font-awesome.min.css';
import '@/components/sidebar.module.css';
import Sidebar from "@/components/sidebar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">


      <body>
        <div style={{display:"flex"}}>      
          <Sidebar/>    
          <main style={{ marginLeft: "250px", padding: "20px", flexGrow: 1 }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
