import 'bootstrap/dist/css/bootstrap.min.css';
import 'font-awesome/css/font-awesome.min.css';
import '@/components/sidebar.module.css';
import Sidebar from "@/components/sidebar";
import "./globals.css";
import { MainContent } from '@/components/mainContent';
import { ParentComponent } from '@/components/sidebar_resize';

export const metadata = {
title: "Create Next App",
description: "Generated by create next app",
};

export default function RootLayout({ children }) {
return (
  <html lang="en">


    <body>
      <div style={{display:"flex"}}>      
        <ParentComponent/>
        <MainContent>
          {children}
        </MainContent>
      </div>
    </body>
  </html>
);
}
